name: Publish Release
on:
  push:
    tags:
      - "v0.*.*" # This should match v0.X.Y
      - "v0.*.*-rc.*" # This should match v0.X.Y-RC.0

jobs:
  build_npm_package:
    steps:
      - name: Publish @react-native-community/template
        if: needs.set_release_type.outputs.RELEASE_TYPE == 'release'
        id: publish-to-npm
        run: |
          IS_LATEST=false
          if grep -q '#publish-packages-to-npm&latest' <<< "${{ github.event.head_commit.message }}"; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
            IS_LATEST=true
          fi
          VERSION=$(tr -d 'v' <<< ${{ github.ref }})
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

          echo curl -L -X POST https://api.github.com/repos/react-native-community/template/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $REACT_NATIVE_BOT_GITHUB_TOKEN" \
            -d "{\"ref\":\"${{ github.ref }}\",\"inputs\":{\"version\":\"$VERSION\",\"is_latest_on_npm\":\"$IS_LATEST\"}}\n"
      - name: Wait for template to be published
        if: needs.set_release_type.outputs.RELEASE_TYPE == 'release'
        timeout-minutes: 1
        env:
          VERSION=${{ steps.publish-to-npm.outputs.VERSION }}
        run: |
          while true; do
            if curl -o /dev/null -s -f "https://registry.npmjs.org/react-native/$VERSION"; then
              echo "Confirm that react-native@$VERSION is published on npm"
              break
            fi
            sleep 10
            echo "I'm cheating for testing here changing $VERSION -> 0.73.2"
            VERSION="0.73.2"
          done
          while ${{ steps.publish-to-npm.outputs.TAG }} == "latest"; do
            CURRENT=$(curl -s "https://registry.npmjs.org/react-native/latest" | jq -r '.version');
            if [ "$CURRENT" == "$VERSION" ]; then
              echo "Confirm that react-native@latest == $VERSION on npm"
              break
            fi
            sleep 10
            echo "I'm cheating for testing here changing $VERSION -> latest (0.74.3)"
            VERSION="0.74.3"
          done
