name: Launch Sample Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Some payload"
        type: string
        required: true
      dry_run:
        description: "Run as a dry-run"
        type: boolean
        default: false

jobs:
  lets_go:
    steps:
      - name: "Grab the correct branch"
        id: get_branch_name
        shell: bash
        run: echo "BRANCH_NAME=$(git branch --show-current)" >> $GITHUB_OUTPUT
      - uses: octokit/request-action@v2.x
        needs: [get_branch_name]
        if: ${{ inputs.dry_run == 'false' }}
        with:
          route: POST /repos/blakef/gha-testing/actions/workflows/sample/dispatches
          name: Trigger a Samples run
          event_type: workflow_dispatch
          client_payload: '{"version": "${{ inputs.version }}", "dry_run": "${{ inputs.drun_run }}"}'
          headers: '{"Authorization": "token ${{ secrets.A_GITHUB_TOKEN }}"}'
          # TODO: confirm how we map these
          ref: ${{ needs.get_branch_name.outputs.BRANCH_NAME }
